#!/bin/bash
source .env

DOMAIN_NAME=${DOMAIN_NAME}
DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME}

NODE_ENV=${NODE_ENV}
TZ=${TZ}

DATABASE_HOST=${DATABASE_HOST}
DATABASE_PATH=${DATABASE_PATH}
DATABASE_NAME=${DATABASE_NAME}
DATABASE_USERNAME=${DATABASE_USERNAME}

MEMCACHE_HOSTNAME=${MEMCACHE_HOSTNAME}
WEBSERVER_HOSTNAME=${WEBSERVER_HOSTNAME}

DATABASE_PORT=${DATABASE_PORT}
MEMCACHE_PORT=${MEMCACHE_PORT}
INTERNAL_PORT_WEBSERVER=${INTERNAL_PORT_WEBSERVER}
INTERNAL_PORT_RUN_THECA_CLIENT=${INTERNAL_PORT_RUN_THECA_CLIENT}

OUTSIDE_PORT_WEBSERVER=${OUTSIDE_PORT_WEBSERVER}
OUTSIDE_PORT_CLIENT=${OUTSIDE_PORT_CLIENT}

SERVER_PROTOCOL=${SERVER_PROTOCOL}
SERVER_PORT=${SERVER_PORT}
